2024-10-09 17:51:06,670 Evaluation process is started.
python "C:\Users\DS1DPC2003M\Desktop\tool\neural_network_console3.10\libs\Python\Lib\site-packages\nnabla\utils\cli\cli.py" forward
	-c "D:\GitHub\SORA-Q\NNC\spresense_cv\data_square_plus\train\square_plus.files\20241009_175100\results.nnp"
	-d "D:\GitHub\SORA-Q\NNC\spresense_cv\dataset6_square_plus\test.csv"
	-o "D:\GitHub\SORA-Q\NNC\spresense_cv\data_square_plus\train\square_plus.files\20241009_175100"
	--replace_path
2024-10-09 17:51:07,859 [nnabla]: [CALLBACK]: Exec forward on local
2024-10-09 17:51:07,878 [nnabla]: Using context "Context(backend=['cpu:float'], array_class='CpuCachedArray', device_id='')"
2024-10-09 17:51:07,928 [nnabla]: data 64 / 106
2024-10-09 17:51:07,943 [nnabla]: data 106 / 106
2024-10-09 17:51:07,955 [nnabla]: Forward Completed.
NNabla command line interface (Version:1.39.0.dev1, Build:231224031435, Callback:NNabla SSH callback module.)
